refactor(apport): Replace global proc_pid_fd by ProcPid
canonical/apport pull request #114
Opened 2023-02-09 18:02 UTC by bdrung

Replace global variable `proc_pid_fd` by an `ProcPid` instance. Instantiate `ProcPid` in `main` before the `is_same_ns` function needs it instead of opening `/proc/{pid}` in `is_same_ns` and later in `get_pid_info`.

2023-04-28 09:01 UTC, bdrung commented
IMO we can ignore codecov/project since the merge reduces the amount of code.

2023-05-01 10:07 UTC, schopin-pro requested changes
I have a design issue that I'd like addressed.

2023-05-01 10:07 UTC, schopin-pro commented on data/apport
> +        )
issue (design): should we really embed a FD in a plain class?

This pattern means we're relying on the finalizer closing out the FD, which sounds like a bad idea to me.

2023-05-01 11:34 UTC, bdrung commented on data/apport
> +        )
Very good point. It will be probably much better to convert that class into a context manager.

2023-07-03 10:58 UTC, schopin-pro reviewed
question: doesn't that open us to race condition?

Disclaimer: I'm really not well-versed in the particulars of procfs, crash-handling, and all the low-level notions here, so I might be raising moot points.

In the previous design, it's fairly obvious that we only open the PID directory once, which I'd assume protects us in case of PID recycling by the kernel (can it recycle the PID of a process that just crashed?). Do we still have that "atomic" property with the new one? I *think* we do, but I can't figure out the call tree well enough to be sure.

2023-07-03 11:49 UTC, bdrung commented
It will not open us to race conditions. We create only one `ProcPid` object for the relevant PID.

2023-07-03 11:51 UTC, merged