ui: upload-time messaging
canonical/apport pull request #123
Opened 2023-02-16 10:37 UTC by schopin-pro

Some crashdb backends might need to display messages to the user, here's a safe API to do so.

See individual commit logs for more detailed descriptions of the changes.

This is an offshoot of #26

2023-02-16 10:52 UTC, schopin-pro commented
V2 patchset changes:
* re-ordering of commits
* formatting
* fold the get_nowait() + thread.join() into a blocking get()
* add missing changes on crashdb implementations. Whoops!

2023-02-16 11:12 UTC, schopin-pro commented
... and a V3 to fix bisectability. Sorry about that :)

2023-02-16 11:20 UTC, bdrung requested changes

2023-02-16 11:20 UTC, bdrung commented on tests/integration/test_ui.py
> +        self.ui.crashdb.upload_delay = 0.2
Shouldn't this current version work without an upload delay?

2023-02-16 11:20 UTC, bdrung commented on tests/integration/test_ui.py
> +        if user_message_callback and self.upload_msg_text:
Can you move this logic into  `apport.crashdb_impl.memory.CrashDatabase`? This implementation is designed for testing.

2023-02-16 11:34 UTC, schopin-pro commented on tests/integration/test_ui.py
> +        self.ui.crashdb.upload_delay = 0.2
Yes it should, the delay was introduced to first make sure the new feature did not break the current common case (i.e. empty polling without messaging).

I can remove it if you prefer, it shouldn't change much.

2023-02-16 11:35 UTC, schopin-pro commented on tests/integration/test_ui.py
> +        if user_message_callback and self.upload_msg_text:
It's not just designed for testing though, as it's used in `bin/dupdb-admin`, hence my reluctance to modify it directly.

2023-02-16 13:37 UTC, bdrung commented on tests/integration/test_ui.py
> +        self.ui.crashdb.upload_delay = 0.2
Yes, please. Having random delays is normally an indication for possible race conditions.

2023-02-16 13:57 UTC, bdrung commented on tests/integration/test_ui.py
> +        if user_message_callback and self.upload_msg_text:
I am undecided where the best place is. The memory `CrashDatabase` has already an `sample_data` option which is clearly only for testing.

2023-02-17 17:17 UTC, schopin-pro commented on tests/integration/test_ui.py
> +        if user_message_callback and self.upload_msg_text:
Moved the feature in the memory database directly.

2023-02-17 17:18 UTC, schopin-pro commented on tests/integration/test_ui.py
> +        self.ui.crashdb.upload_delay = 0.2
I reimplemented the tests entirely in 3 separate tests rather than hogging an already existing test. One has no delay, no msg, one has delays, one has msgs.

2023-02-17 21:15 UTC, bdrung commented on apport/ui.py
> +            message_queue.put((title, text, message_displayed))
suggestion: Instead of using a tuple, a dataclass could be used.

2023-02-17 21:15 UTC, bdrung commented on apport/ui.py
> +            message_queue.put((title, text, message_displayed))
Merging anyway.

2023-02-17 21:16 UTC, merged