refactor: add _write_asc_to_file
canonical/apport pull request #188
Opened 2023-05-18 08:26 UTC by BMaxV

Hello,

here is another one. Should be straight forward. 

Something I noticed when looking at this, was that `fileutils` constructs the path name and opens the file. And then the file handle gets passed around. That surprised me a bit , I would have expected something like:

```
my_data = some_function()
my_path = path_creation_function()
with open(my_path) as f:
    f.write(my_data)
```

Should that be a todo for the future?

2023-05-19 09:26 UTC, bdrung requested changes
Thanks for your merge request.

The Apport project is covered by Canonical’s contributor agreement (see https://canonical.com/projects/directory). Before I can merge the change, you need to sign the [Canonical’s contributor agreement](https://www.ubuntu.com/legal/contributors).

TODO for myself: Add a contribution document stating that the contributor agreement needs to be signed and check it with the CI.

2023-05-19 09:26 UTC, bdrung commented on problem_report.py
> +    def _write_asckeys_to_file(
suggestion: `asckeys` is a little cryptic. How about using the long form `ascii_keys`?

2023-05-19 09:26 UTC, bdrung commented on problem_report.py
> +        # write the ASCII keys first
suggestion: Shouldn't this comment stay in the calling function?

2023-05-19 09:26 UTC, bdrung commented on problem_report.py
> +        for k in asckeys:
nitpick/suggestion: To reduce the level of indentation in this method, the for loop could be moved out of this method (by either keeping the loop in the calling function or add another function just for looping over it).

2023-05-19 09:47 UTC, bdrung commented
Forgot to mention: Open the file in one function and requiring the caller to close it is a bad pattern. So improving that is welcome (but beware to not break the API).

2023-05-19 14:19 UTC, BMaxV commented on problem_report.py
> +        # write the ASCII keys first
I can put it there.

In the end the function should look something like:

```
def write(self, file, only_new=False):
    self._get_sorted_keys(only_new)()
    self._write_asci()
    self._write_binary()
    self._rest()
```

_write_binary() https://github.com/canonical/apport/blob/main/problem_report.py#L437
_rest() https://github.com/canonical/apport/blob/main/problem_report.py#L514

write binary might have it's subfunctions too. 

It should be really obvious that this is happening first and ASCII is right in the name. 

This:

```
def write(self, file, only_new=False):
    self._get_sorted_keys(only_new)()
    # write ascii first
    self._write_asci()
    # write binary second
    self._write_binary()
    self._rest()
```

 wouldn't need the comment.

2023-05-19 14:57 UTC, bdrung commented on problem_report.py
> +        # write the ASCII keys first
suggestion: Yes, the final write method will be small enough to understand it without that comment. Adding a comment there will reduce the readability. So I suggest to drop that comment completely.

2023-05-20 08:07 UTC, BMaxV commented
I sent the contributor agreement as well.

2023-05-20 12:41 UTC, bdrung approved these changes
Thanks. Last request before merging: Can you squash the two commits since we are using fast-forward merges?

2023-05-20 12:41 UTC, bdrung commented on problem_report.py
> +    def _write_ascii_key_to_file(
nitpick(name): The name just says that it will write the key, but it writes the key and the ASCII value. So `_write_key_and_ascii_value_to_file` would decribe it more precisely.

2023-05-21 08:21 UTC, BMaxV commented
I did both. :)

2023-05-22 11:23 UTC, bdrung commented
Thanks, but the git commit message plus message body does not match the diff any more (renamed method). Can you rewrite the git commit message to reflect the current name?

2023-05-22 14:18 UTC, merged