Deb822 1
canonical/apport pull request #203
Opened 2023-07-12 13:12 UTC by schopin-pro

THis PR is for bisecting the coverage changes in #193

2023-07-12 16:53 UTC, bdrung commented on tests/system/test_packaging_apt_dpkg.py
> +    # pylint: disable=unused-argument
question: Why do you add `apt_style` as parameter here?

2023-07-12 16:53 UTC, bdrung commented on tests/system/test_packaging_apt_dpkg.py
> +        pass
How about raising NotImplemented in the else case (with a `# pragma: no cover` for the else case)?

2023-07-12 16:53 UTC, bdrung commented on tests/system/test_packaging_apt_dpkg.py
> +    apt_style: typing.Literal["one-line"],
suggestion: How about adding the type hints for the other parameters?

2023-07-12 17:02 UTC, schopin-pro commented on tests/system/test_packaging_apt_dpkg.py
> +    # pylint: disable=unused-argument
Because parameters aren't optional, contrary to fixtures. I preferred having an unused argument here rather than have to parametrize every other test individually :)

2023-07-12 17:04 UTC, schopin-pro commented on tests/system/test_packaging_apt_dpkg.py
> +    expected_content = ["sources.list.d", "trusted.gpg.d"]
It's just the way the code evolved. I guess that would be the natural next step ;)

2023-07-12 17:05 UTC, schopin-pro commented on tests/system/test_packaging_apt_dpkg.py
> +        pass
NACK. This will be changed to an actual implementation a few commits down the line, and it doesn't change anything to pass vs raise.

2023-07-12 17:07 UTC, schopin-pro commented on tests/system/test_packaging_apt_dpkg.py
> +    apt_style: typing.Literal["one-line"],
If you want extra type hints in my commits, you better come with a ready-to-click suggestion, my friend ;)

2023-07-12 17:17 UTC, schopin-pro commented on tests/system/test_packaging_apt_dpkg.py
> +    assert set(os.listdir(os.path.join(configdir, release))) == set(
Done.

2023-07-12 17:17 UTC, schopin-pro commented on tests/system/test_packaging_apt_dpkg.py
> +    apt_style: typing.Literal["one-line"],
Done, since I had to edit that commit anyway ;)

2023-07-12 20:08 UTC, bdrung commented on tests/system/test_packaging_apt_dpkg.py
> +    # pylint: disable=unused-argument
Thanks for the explanation. How about using `disable-next` here?

2023-07-12 20:09 UTC, bdrung commented on tests/system/test_packaging_apt_dpkg.py
> +    apt_style: typing.Literal["one-line"],
I came with https://github.com/canonical/apport/pull/201 ;)

2023-07-13 09:24 UTC, bdrung requested changes
I finished the review of all commits. Except for some minor comment, the change looks good. I would love to see moving to pathlib (to make the code shorter and easier to read), but this is something for the future.

2023-07-13 09:24 UTC, bdrung commented on apport/packaging_impl/apt_dpkg.py
> +        assert origin.startswith("LP-PPA-")
issue: Was that change intentional? Before this commit create_ppa_source_from_origin would return `None` if origin does not start with `LP-PPA-`. With this change is will raise an assertion error. I would have expected:
```python3
if not origin.startswith("LP-PPA-"):
    return None
```

2023-07-13 09:24 UTC, bdrung commented on apport/packaging_impl/apt_dpkg.py
> +    ) -> Optional[list[SourceEntry]]:
todo: Changing the signature requires to change the docstring as well.

2023-07-13 09:24 UTC, bdrung commented on apport/packaging_impl/apt_dpkg.py
> +                    for elt in source_list_content:
question: What does `elt` stand for?

2023-07-13 09:36 UTC, schopin-pro commented on apport/packaging_impl/apt_dpkg.py
> +        assert origin.startswith("LP-PPA-")
Good point. I used to have a guard in create_ppa-source_from_origin for the prefix, but it was dropped at some point. Will be fixed in the next push.

2023-07-13 09:41 UTC, schopin-pro commented on apport/packaging_impl/apt_dpkg.py
> +    ) -> Optional[list[SourceEntry]]:
FIxed in upcoming push.

2023-07-13 09:45 UTC, schopin-pro commented on apport/packaging_impl/apt_dpkg.py
>          raise SystemError(
ACK. Fixed in next push.

2023-07-13 09:45 UTC, schopin-pro commented on apport/packaging_impl/apt_dpkg.py
> +            "no configured source contains the `deb` type."
Fixed in next push.

2023-07-13 10:07 UTC, schopin-pro commented on apport/packaging_impl/apt_dpkg.py
> -            raise SystemError(f"{apt_sources} does not exist")
Honestly, I dropped this because it's a fairly low-evidence check, and with `apt_dir` it's even worse (directory existence doesn't mean there's actual config files), and the exception itself is way too generic to be useful. If the directory doesn't exist we're going to have exceptions down the line anyway.

The fact that I didn't have to modify any test when I dropped it comforted me in that decision.

2023-07-13 10:26 UTC, bdrung commented on apport/packaging_impl/apt_dpkg.py
> -            raise SystemError(f"{apt_sources} does not exist")
Thanks for the explanation. It would be great to have that explanation in the commit message for future explanation.

2023-07-13 10:34 UTC, bdrung commented on apport/packaging_impl/apt_dpkg.py
> +            "cannot determine default mirror:"
```suggestion
            f"cannot determine default mirror:"
```
Probably a linter will complain about that.

2023-07-13 10:38 UTC, bdrung commented on apport/packaging_impl/apt_dpkg.py
> +    ) -> Optional[list[SourceEntry]]:
You also renamed `release_codename` to `codename`.

2023-07-13 10:42 UTC, bdrung commented on apport/packaging_impl/apt_dpkg.py
> +            "cannot determine default mirror:"
Hm, pylint does not complain about that and that string plus f-string concatenation seems to work. So you can ignore that.

2023-07-13 12:05 UTC, schopin-pro commented on apport/packaging_impl/apt_dpkg.py
> +    ) -> Optional[list[SourceEntry]]:
Fixed (by reverting the rename)

2023-07-13 13:15 UTC, merged