problem_report: separate base64 encoding and gzip compression
canonical/apport pull request #242
Opened 2023-10-31 15:57 UTC by schopin-pro

Refactor _write_key_and_binary_value_compressed_and_encoded_to_file into a generator taking in all sorts of data and compressing and splitting it into byte chunks, and a function encoding an iterable of binary chunks into an RFC822 base64 field.

The compression generator is still in need of further refactoring, but it's still a step in the right direction.

2023-10-31 16:28 UTC, bdrung requested changes

2023-10-31 16:28 UTC, bdrung commented on problem_report.py
> +        """
That method description needs to be updated to reflect the new code.

2023-10-31 16:28 UTC, bdrung commented on problem_report.py
> +                file.write(b"\n")
```suggestion
            file.write(f"{key}: base64".encode("ASCII"))
            for chunk in chunks:
                file.write(b"\n ")
                file.write(base64.b64encode(chunk))
            file.write(b"\n")
```

2023-10-31 16:28 UTC, bdrung commented on problem_report.py
> +        if hasattr(value, "find"):
suggestion: The rename of `v` to `value` could go into a separate commit to make the diff easier to read.

2023-10-31 16:37 UTC, schopin-pro commented on problem_report.py
> +    def _write_base64_encoded_binary_chunks(
I personally don't find it particularly misleading, but I welcome any suggestion :)

2023-10-31 16:56 UTC, schopin-pro commented on problem_report.py
> +        if hasattr(value, "find"):
It was easier to do it rather than find the words to explain why I though it was a slightly bad idea long term :)

2023-10-31 16:59 UTC, schopin-pro commented on problem_report.py
> +                file.write(b"\n")
Oooh, subtle!

2023-10-31 17:26 UTC, bdrung commented on problem_report.py
> +    def _write_base64_encoded_binary_chunks(
We have these similar functions:
* _write_key_and_ascii_value_to_file
* _write_base64_encoded_binary_chunks
* _write_key_and_binary_value_compressed_and_encoded_to_file

These names are all suboptimal. At least _write_key_and_binary_value_compressed_and_encoded_to_file and _write_base64_encoded_binary_chunks should be named consistently.

2023-10-31 17:27 UTC, bdrung approved these changes
Besides the `_write_base64_encoded_binary_chunks` name, this PR is ready to be merged.

2023-11-04 12:50 UTC, schopin-pro commented on problem_report.py
> +    def _write_base64_encoded_binary_chunks(
I went for `_write_key_and_base64_binary_chunks`.

2023-11-04 17:43 UTC, bdrung approved these changes

2023-11-04 17:44 UTC, merged