refactor: Split Report.standard_title into smaller methods
canonical/apport pull request #250
Opened 2023-11-06 12:16 UTC by bdrung

Split `Report.standard_title` into smaller methods by introducing `Report._python_exception_title` and `Report._signal_crash_title`.

2023-12-06 15:37 UTC, schopin-pro requested changes
LGTM on principle but there's a naming issue that bugged me.

2023-12-06 15:37 UTC, schopin-pro commented on apport/report.py
> +    def _signal_crash_title(self) -> Optional[str]:
suggestion: use an actual verb in the name to avoid ambiguity, e.g. `_get_signal_crash_title()`

At first I thought the method was about *sending* a signal.

2023-12-07 17:01 UTC, schopin-pro commented
Can you resolve the conflicts?

2023-12-07 17:06 UTC, bdrung commented
Rebased and resolved conflict.

2023-12-08 10:28 UTC, merged