Add GitHub backend for WSL and snaps
canonical/apport pull request #26
Opened 2022-11-23 16:16 UTC by nteodosio

This builds on Edu's work on https://github.com/canonical/apport/pull/1, to add this functionality: If a snap contact: field points to Github, report it there.

The snap report can be tested by installing [this snap](https://github.com/canonical/snap-for-apport-reports/) and then running `apport-bug apport-target`.

2022-11-23 19:49 UTC, nteodosio commented
Tests will be added once/if the principle is accepted.

2022-12-05 10:25 UTC, bdrung commented
The principle concept looks good to me (at least I fail to come up with a complaint :laughing:). So from my side you can continue with test cases and atomic commits.

2022-12-05 10:40 UTC, seb128 commented
Simon asked for some context. The goal is to allow users to report issues against github projects instead of launchpad using ubuntu-bug which ensure we have the details and log we need. 

While launchpad provide an natural place to report bugs against packages from the archive that's not true for snap. We workarounded that by creating upstream projects on launchpad and redirecting ubuntu-bug there but if the project is actually maintained in github we end up in a situation where the reports go not to the ubuntu package, nor the upstream project but yet another place which is not ideal.

The logic would be for snaps to respect the 'contact' information defined in the snap, if that points to github then direct report the issue there using the github device flow, https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps#device-flow. The API key is going to be owned by Canonical IS since the project is under the Canonical org

2022-12-05 11:02 UTC, schopin-pro commented
Allow me to run a scenario to see if I understood things correctly.

Let's take the `lxd` snap, which seems to be the only Canonical snap on my system that has a contact URL pointing to GH.

* `ubuntu-bug lxd`, it gathers system info, I get the usual window with the recap of all the data, I click on "send it".
* My browser (let's say Firefox snap) opens to gh.com/lxc/lxd/issues/new with a pre-filled form with all the data that we want
  - If I'm already logged in, it'll be reported under my login?
  - If I'm not logged in it'll be reported as canonical? If so, what can they do with those permissions?

2022-12-05 19:49 UTC, seb128 commented
> * If I'm not logged in it'll be reported as canonical? If so, what can they do with those permissions?

I'm guessing the question is in reaction to me stating that the API key is owned by Canonical? The key is used to identify the client software, it allows github to identify problematic clients but also to limit the number of requests according to your type of subscription. The bug is submitted by the user using their own account

2023-01-09 16:45 UTC, nteodosio commented
I'm having trouble adding tests for `add_snap_info`. This test would require snaps to be installed, but trying [causes an error in the Github CI](https://github.com/nteodosio/apport/actions/runs/3875810090/jobs/6608860480#step:4:1629):

> error: cannot communicate with server: Post "http://localhost/v2/snaps": dial unix /run/snapd.socket: connect: no such file or directory

It seems that [this is a known problem](https://stackoverflow.com/a/55804965).

Any idea on how to work around it?

2023-01-09 17:23 UTC, bdrung commented
You can write unit tests and you could write integration/system tests where you mock the snap parts.

2023-01-17 18:33 UTC, nteodosio commented
Is github.py supposed to be covered?

2023-01-20 10:42 UTC, bdrung commented
Yes,  `github.py` should be covered. `launchpad.py` has test cases which are currently not run in CI. I am working on making them running by using python3-vcr.

2023-01-25 12:22 UTC, nteodosio commented
@seb128, was the API key provided yet?

2023-02-08 16:35 UTC, bdrung commented on etc/apport/crashdb.conf
> +    'snap-github': {
Is that GitHub report tied to snaps?

2023-02-09 10:33 UTC, nteodosio commented on etc/apport/crashdb.conf
> +    'snap-github': {
Yes, only for snaps.

2023-02-09 11:07 UTC, schopin-pro reviewed
Looks fairly good to me, except for the one issue I have with `external_login`.

2023-02-09 11:07 UTC, schopin-pro commented on apport/crashdb.py
> +
suggestion: remove this API method, fold its content into the  `upload` method instead.

I see the login requirement as an implementation detail of the upload process for this particular backend, not a generic step common to all/most backends.

Furthermore, having it as part of the `upload` method would move it out of the main thread, which makes for a better user experience.

2023-02-09 12:43 UTC, nteodosio commented on apport/crashdb.py
> +
Since it requires `ui`, we would have to change the signature of `upload` and all its calls. Is that desirable?

2023-02-09 14:57 UTC, schopin-pro requested changes
I must confess, my previous review was a bit on the light side, because first I'm not familiar with this area of the code, second @bdrung  already had done a review, and finally it was right before lunch.

Now that I have eaten, my previous comment regarding `external_login` and @nteodosio 's answer kind of morphed into a bigger thing.

2023-02-09 14:57 UTC, schopin-pro commented on apport/ui.py
> +
issue: this should not be in generic UI code.

The whole point of separating the crash upload into the crashdb interface is to have the rest of the code be blissfully aware of it, having a `ui_github_login` method in the generic UI code sort of flies in the face of it.

2023-02-09 14:57 UTC, schopin-pro commented on apport/crashdb.py
> +
I'm really not a big fan of having the crashdb implementation driving the UI, since it's supposed to be the other way around.

AFAICT your UI needs boil down to displaying a message to the user, right? If so, how about we "simply" add a new callback to `upload` , e.g. 

```python
    def upload(self, report, progress_callback=None, user_message_callback: Optional[Callable[[], str]] = None):
        pass
```

WDYT?

2023-02-09 15:59 UTC, nteodosio commented on apport/crashdb.py
> +
That looks like a better solution indeed. @EduardGomezEscandell, is it OK for you?

2023-02-09 16:45 UTC, EduardGomezEscandell commented on apport/crashdb.py
> +
Yeah go ahead. Feel free to make any changes to my code :)

2023-02-13 14:29 UTC, nteodosio commented
I addressed the review comments. I added separate commits which I can squash to the corresponding previous ones if this looks good.

2023-02-14 17:21 UTC, schopin-pro requested changes
It looks much better!

However, there's still the threading issue to contend with: the `upload` code is in a different thread than the UI, so using `self.ui` in the callback could be a source of issues down the road.

See https://github.com/schopin-pro/apport/tree/wsl where I have stacked up a few commits to change (and add tests). Feel free to pull them in :)

2023-02-14 19:34 UTC, nteodosio commented
Thanks! I did so.

2023-02-15 16:08 UTC, bdrung requested changes

2023-02-15 16:48 UTC, nteodosio commented on etc/apport/crashdb.conf
> +        'github_app_id': 'a654870577ad2a2ab5b1', # TODO: Give App ownership to a Canonical github account
@seb128 might know?

2023-02-16 10:50 UTC, schopin-pro commented
@nteodosio FYI, @bdrung asked me yesterday to split off the new upload-time msg API into a separate PR for ease of review, and to basically get the ball rolling. So that's at #123 :)

2023-02-16 11:18 UTC, seb128 commented on etc/apport/crashdb.conf
> +        'github_app_id': 'a654870577ad2a2ab5b1', # TODO: Give App ownership to a Canonical github account
I got a reply from IS, I will follow up on that later today just need to figure out some details

2023-02-17 11:37 UTC, nteodosio commented
Alright, once that one is merged I'll rebase.

2023-02-17 12:18 UTC, bdrung commented on etc/apport/crashdb.conf
> +        'distro': 'ubuntu wsl'
For consistency that should be `Ubuntu WSL` or `Ubuntu on WSL`

2023-02-17 12:23 UTC, nteodosio commented on etc/apport/crashdb.conf
> +        'distro': 'ubuntu wsl'
Hmm, I fail to see the pattern there. All other `distro:` lines use lowercase. Can you please clarify?

2023-02-17 12:33 UTC, bdrung commented on etc/apport/crashdb.conf
> +        'distro': 'ubuntu wsl'
I looked at the code again and made a mistake. This `distro` is not the related to `DistroRelease`. This `distro` is the name of the distribution in Launchpad (see doc/crashdb-conf.md). So this `distro` field is useless for the github implementation and can be dropped.

2023-02-17 12:37 UTC, bdrung commented
Can you add an entry for the github crash database to `doc/crashdb-conf.md`?

2023-02-17 12:39 UTC, bdrung commented
How do you test that? I want to see the code in action before merging.Do you have a test repository to file bugs against?

2023-02-17 12:44 UTC, nteodosio commented
> Can you add an entry for the github crash database to doc/crashdb-conf.md?

Sure.

> How do you test that?

Added that to the pull request first post for visibility.

2023-02-20 10:34 UTC, bdrung commented
https://github.com/canonical/apport/pull/123 is merged. Can you rebase on main?

2023-02-23 11:04 UTC, nteodosio commented
Done, thanks for the heads-up.

2023-02-23 11:35 UTC, schopin-pro commented
Please fix the tests? The skip-tests action fails with the following problem:

```
Run python3 -m pytest -ra --cov=$(pwd) --cov-report=xml tests/
============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
rootdir: /__w/apport/apport
plugins: cov-3.0.0
collected 488 items / 1 error / 487 selected

==================================== ERRORS ====================================
______________ ERROR collecting tests/integration/test_github.py _______________
ImportError while importing test module '/__w/apport/apport/tests/integration/test_github.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/integration/test_github.py:13: in <module>
    import apport.crashdb_impl.github
apport/crashdb_impl/github.py:16: in <module>
    import requests
E   ModuleNotFoundError: No module named 'requests'

---------- coverage: platform linux, python 3.10.6-final-0 -----------
Coverage XML written to file coverage.xml

=========================== short test summary info ============================
ERROR tests/integration/test_github.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 2.59s ===============================
```

2023-02-23 11:50 UTC, bdrung requested changes
I'll test this code now against your repository. My plan is to merge the change today or tomorrow and cut a release and upload to Ubuntu to get it in before the feature freeze.

2023-02-23 11:50 UTC, bdrung commented on apport/crashdb.py
> +    def external_login(self, user_message_callback):
Since we are using a message_callback now, the `external_login` does not need to be part of the public CrashDB.

2023-02-23 11:50 UTC, bdrung commented on apport/crashdb_impl/github.py
> +    def external_login(self, user_message_callback):
Since we are using a message_callback now, the external_login does not need to be part of the public CrashDB and it could be named more specific now: `github_login`.

2023-02-23 11:50 UTC, bdrung commented on apport/crashdb_impl/github.py
> +        prompt += "Code: {code}"
```suggestion
        prompt = (
            "Posting an issue requires a Github account. If you have "
            "one, please follow these steps to log in.\n"
            "\n"
            "Open the following URL. When requested, write this code "
            "to enable apport to open an issue.\n"
            "URL:  {url}\n"
            "Code: {code}"
        )
```

2023-02-23 11:50 UTC, bdrung commented on apport/crashdb_impl/github.py
> +        prompt += "Code: {code}"
Or even use f-strings:
```suggestion
        prompt = (
            f"Posting an issue requires a Github account. If you have "
            f"one, please follow these steps to log in.\n"
            f"\n"
            f"Open the following URL. When requested, write this code "
            f"to enable apport to open an issue.\n"
            f"URL:  {response['verification_uri']}\n"
            f"Code: {response['user_code']}"
        )
```

2023-02-23 18:47 UTC, bdrung commented on apport/ui.py
> +
One unneeded added newline.

2023-02-23 20:10 UTC, bdrung approved these changes

2023-02-23 20:10 UTC, merged

2023-02-23 21:43 UTC, bdrung commented
Fix for binary content in some Snap fields: https://github.com/canonical/apport/pull/133