test: add test_crash_suid_dumpable_debug
canonical/apport pull request #284
Opened 2024-01-09 14:09 UTC by bdrung

To increase the code coverage add a test for
`/proc/sys/fs/suid_dumpable` set to 1 ("debug") and crashing a set-user-ID (suid) program.

Is that the intended behavior?

2024-01-09 14:28 UTC, schopin-pro commented on tests/integration/test_signal_crashes.py
> +        resource.setrlimit(resource.RLIMIT_CORE, (-1, -1))
nitpick: the comment doesn't match the line.

2024-01-09 14:28 UTC, schopin-pro commented on tests/integration/test_signal_crashes.py
> +        self.do_crash(command="/bin/ping", args=["127.0.0.1"], uid=8, suid_dumpable=1)
question: is there a guarantee that UID 8 is `mail` and even present on the test system?

2024-01-09 16:08 UTC, bdrung commented
I checked what systemd-coredump is doing: It writes the core file as root and does not allow the user to read it in case of suid processes:
```
        /* We don't allow users to read coredumps if the uid or capabilities were changed. */
        if (!allow_user)
                return 0;
```

2024-01-09 16:17 UTC, bdrung commented on tests/integration/test_signal_crashes.py
> +        self.do_crash(command="/bin/ping", args=["127.0.0.1"], uid=8, suid_dumpable=1)
base-files relies on the `mail` user to be present. So it will be on the test systems. On Debian/Ubuntu `mail` is always UID 8, but I failed to find the component that is responsible for the initial content of `/etc/passwd`.

2024-02-13 13:20 UTC, schopin-pro requested changes
Almost there! It seems there was a typo or something?

2024-02-13 13:20 UTC, schopin-pro commented on tests/integration/test_signal_crashes.py
> +MAIL_UID = 8
praise: thanks for that, makes it easier to understand

Also should make it easier to change it down the line should we come upon circumstances where the mail UID is *not* 8.

2024-02-13 13:20 UTC, schopin-pro commented on tests/integration/test_signal_crashes.py
> +    def test_crash_setuid_(self):
issue: you dropped the `drop` part of the test name?

2024-02-14 13:43 UTC, merged