refactor(apport): split main into smaller parts
canonical/apport pull request #300
Opened 2024-02-14 15:30 UTC by bdrung

These refactoring are preparation work for https://github.com/canonical/apport/pull/290.

2024-02-14 16:05 UTC, bdrung commented
IMO codecov can be ignored in this case.

2024-02-16 09:48 UTC, schopin-pro requested changes
A small nitpick and a naming issue.

2024-02-16 10:04 UTC, bdrung commented on data/apport
> +
Valid point. Changed the commit message.

2024-02-16 10:05 UTC, bdrung commented on data/apport
> +def _check_global_pid_and_forward(options: argparse.Namespace) -> bool:
That function is a mess. It does check and changes. I fail to find an easy way to split this function into parts that can be easily named. So I converted and extended the first comment into a docstring.

2024-02-16 10:52 UTC, schopin-pro commented on data/apport
> +def _check_global_pid_and_forward(options: argparse.Namespace) -> bool:
I'll take it!

2024-02-16 10:52 UTC, merged