report: use library search order from ld.so
canonical/apport pull request #354
Opened 2024-06-13 20:58 UTC by bdrung

Use the same library search order from `ld.so`:

```
$ ld.so --help
[...]
Shared library search path:
  (libraries located via /etc/ld.so.cache)
  /lib/x86_64-linux-gnu (system search path)
  /usr/lib/x86_64-linux-gnu (system search path)
  /lib (system search path)
  /usr/lib (system search path)
```

2024-06-21 09:16 UTC, schopin-pro requested changes

2024-06-21 09:16 UTC, schopin-pro commented on apport/report.py
> +                    f"{gdb_sandbox}/lib"
issue: Rather than a hardcoded list, shouldn't we actually *query* the local ld.so to get the search order?

2024-07-11 10:44 UTC, bdrung commented on apport/report.py
> +                    f"{gdb_sandbox}/lib"
You asked for it. Now you get a bigger merge request!

2024-07-11 13:25 UTC, bdrung commented
Problem with the implementation: jammy does not ship `/usr/bin/ld.so`.

2024-07-11 13:44 UTC, schopin-pro commented
I didn't even remember that `/usr/bin/ld.so` was a thing. Maybe just use `/lib/$triplet/ld.*\.so\..*`?

2025-06-02 12:07 UTC, merged