Fix retrace tests on non-amd64 (FR-8039)
canonical/apport pull request #359
Opened 2024-06-28 14:13 UTC by schopin-pro

There are a few assumptions made by the test code that only are true on amd64 :)

See https://bugs.launchpad.net/ubuntu/+source/apport/+bug/2069815

Note that we'll probably want to install gdb-multiarch in debian/tests/control in the packaging.

2024-07-02 09:28 UTC, bdrung commented on tests/system/test_apport_retrace.py
> +def test_retrace_system_sandbox_gdb_sandbox_nonamd64(
This test is not executed in the CI. Could we convert it into a unit test and mock the architecture?

2024-07-02 09:40 UTC, schopin-pro commented on tests/system/test_apport_retrace.py
> +def test_retrace_system_sandbox_gdb_sandbox_nonamd64(
I'd rather not. Basically, you want to make the test less meaningful for the convenience of running it on the GH CI. I'd much rather have this code path exercised for *real* in the Ubuntu CI, if less frequently.

2024-07-04 10:51 UTC, bdrung requested changes

2024-07-04 10:51 UTC, bdrung commented on tests/system/test_apport_retrace.py
> +    """Retrace a divide-by-zero crash in a system sandbox with a GDB sandbox."""
todo: It has the same description that the copy-paste origin.

2024-07-04 10:51 UTC, bdrung commented on tests/system/test_apport_retrace.py
> +    ret = subprocess.run(cmd, check=False, env=env, capture_output=True)
suggestion: you could use `text=True` no avoid the `.decode()` later.

2024-07-04 10:51 UTC, bdrung commented on tests/system/test_apport_retrace.py
> +    reason="GDB sandbox only available on amd64",
nitpick: this reason is confusing, but i fail to come up with a clearer wording

2024-07-04 10:51 UTC, bdrung commented on tests/system/test_apport_retrace.py
> +    # jammy: at ./divide-by-zero.c
There seems to be missing something from the first comment line. In the code snippet that I have from our coding session I have following instead:
```
    # The path could be relative to the source code (with or without
    # a leading "./") or it can be absolute with
    # /usr/src/<deb-source>-<deb-version>/
```

2024-07-04 10:51 UTC, bdrung commented on tests/system/test_apport_retrace.py
>          stack_top = "divide_by_zero () at ./divide-by-zero.c"
suggestion: Instead of those, we can accept all variants in a regular expression:
```
    frame_regex = re.compile(
        r"^#0  (0x[0-9a-b]+ in )? divide_by_zero \(\)"
        r" at (/usr/src/chaos-marmosets-[^/]+/|./)?divide-by-zero.c:[0-9]+$",
        flags=re.M,
    )
    stack_regex = re.compile(
        r"^divide_by_zero \(\)"
        r" at (/usr/src/chaos-marmosets-[^/]+/|./)?divide-by-zero.c:[0-9]+$",
        flags=re.M,
    )
```

2024-07-04 10:51 UTC, bdrung commented on tests/system/test_apport_retrace.py
>      assert stack_top in report["StacktraceTop"]
The comment above: `# noble armhf: at divide-by-zero.c`. So this assertion will probably fail on armhf.

2024-07-04 10:52 UTC, bdrung commented on tests/system/test_apport_retrace.py
> +def test_retrace_system_sandbox_gdb_sandbox_nonamd64(
Okay.

2024-07-04 11:57 UTC, schopin-pro commented on tests/system/test_apport_retrace.py
> +    reason="GDB sandbox only available on amd64",
So do I.

2024-07-04 12:00 UTC, schopin-pro commented on tests/system/test_apport_retrace.py
> +    # jammy: at ./divide-by-zero.c
Right, I think you wrote that comment, because I have no memory of it (I think I don't pay much attention to comments when reviewing my commits. I should work on that.)

2024-07-04 12:14 UTC, schopin-pro commented on tests/system/test_apport_retrace.py
>      assert stack_top in report["StacktraceTop"]
That should be handled by your suggestion, thanks!

2024-07-04 12:16 UTC, bdrung commented on tests/system/test_apport_retrace.py
> +        r"^#0  (0x[0-9a-b]+ in )? divide_by_zero \(\)"
my bad: I broke the hex-value expression.
```suggestion
        r"^#0  (0x[0-9a-f]+ in )? divide_by_zero \(\)"
```

2024-07-04 12:18 UTC, bdrung commented on tests/system/test_apport_retrace.py
> +    reason="GDB sandbox only available on amd64",
```suggestion
    reason="GDB sandbox is available on amd64",
```

2024-07-04 12:21 UTC, schopin-pro commented on tests/system/test_apport_retrace.py
> +        r"^#0  (0x[0-9a-b]+ in )? divide_by_zero \(\)"
Boooo, bad bdrung ;).
I also spotted another small mistake (a non-escaped `.`) a little further down.

2024-07-04 12:22 UTC, schopin-pro commented on tests/system/test_apport_retrace.py
> +        r"^#0  (0x[0-9a-b]+ in )? divide_by_zero \(\)"
Also, I know where that's from. That's actually my original mistake that I fixed back when I created the commits, but that was after our pairing session so your local copy never got the fix.

2024-07-04 12:22 UTC, bdrung commented on tests/system/test_apport_retrace.py
> +        r"^#0  (0x[0-9a-b]+ in )? divide_by_zero \(\)"
Since frame_regex is a longer version of stack_regex, you might want to deduplicate the code.

2024-07-08 13:04 UTC, schopin-pro commented on tests/system/test_apport_retrace.py
> +        r"^#0  (0x[0-9a-b]+ in )? divide_by_zero \(\)"
I thought about it already, but the easy path was thwarted by the `^` and then the dedup code was beginning to be a bit too ugly, so I decided to scrap it.

2024-07-19 17:03 UTC, bdrung approved these changes
The changes look good.

I'll verify that these changes plus other commits will make the test succeed on all archs via apport 2.29.0+git20240719b-0ubuntu1~ppa1 in https://launchpad.net/~bdrung/+archive/ubuntu/apport

Once those autopkgtests are green, I'll merged this PR.

2024-07-24 21:38 UTC, bdrung commented
After fixing the memory consumption of apport-retrace, these tests succeed on arm64, armhf, ppc64el. Only s390x fails to retrace (but that looks like a separate issue). So we are good to go.

2024-07-24 21:38 UTC, merged