apport-retrace: exit without 0 on error
canonical/apport pull request #360
Opened 2024-07-09 10:50 UTC by bdrung

Exit `apport-retrace` with return code 2 in case the report is malformed and with return code 3 on known errors. Crashes of `apport-retrace` will exit with return code 1.

2024-07-10 14:37 UTC, schopin-pro requested changes
Very  nice, except for the load_report() bit where we're missing the opportunity to remove a raw exit() call.

2024-07-10 14:37 UTC, schopin-pro commented on bin/apport-retrace
> +                sys.exit(2)
issue: it's a shame to have main() return an int but still have a hard exit() call in `load_report()`. How about throwing an exception instead, in proper Python fashion?

2024-07-10 14:37 UTC, schopin-pro commented on bin/apport-retrace
> +def main(argv):
praise: Nice, makes it easier to test!

2024-07-10 15:31 UTC, bdrung commented on bin/apport-retrace
> +                sys.exit(2)
Okay. Introduced `_LoadReportException`.

2024-07-12 09:50 UTC, schopin-pro approved these changes

2024-07-12 09:50 UTC, merged