launchpad: don't systematically order retrace on private reports (FR-7945)
canonical/apport pull request #367
Opened 2024-07-16 17:27 UTC by schopin-pro

Just because a report is marked as LaunchpadPrivate and has an actual
architecture attached to it doesn't mean it should be retraced. A
contrario, any report that is designated as LaunchpadPrivate should be
marked as private, even if get_os_info() was never called on it.

Fixes https://bugs.launchpad.net/ubuntu/+source/apport/+bug/2068933

The review will be much easier if done commit-wise.

2024-07-17 13:06 UTC, bdrung requested changes

2024-07-17 13:06 UTC, bdrung commented on apport/crashdb_impl/launchpad.py
> +        if "LaunchpadPrivate" in report:
question: Shouldn't the LaunchpadPrivate check done before the DistroRelease check?

2024-07-17 13:06 UTC, bdrung commented on apport/crashdb_impl/launchpad.py
> +    def _generate_upload_headers(self, report: apport.report.Report) -> dict[str, str]:
praise: Splitting out the header generation is nice.

2024-07-17 13:06 UTC, bdrung commented on apport/crashdb_impl/launchpad.py
> +    def _enforce_privacy_for_distro_reports(
This method name is misleading. It does not tell me that it also sets Subscribers and Tags. idea: maybe split this function into two: one just for checking for privacy and the other(s) for the retrace/duplicate checks.

2024-07-17 14:10 UTC, schopin-pro commented on tests/unit/test_launchpad.py
> +print(_f(5))
Not sure, I lifted this from another test file :D

2024-07-17 14:11 UTC, schopin-pro commented on apport/crashdb_impl/launchpad.py
> +        if "LaunchpadPrivate" in report:
Maybe? I don't really want to change the logic too much here unless someone explicitly starts to complain.

2024-07-17 14:15 UTC, bdrung commented on apport/crashdb_impl/launchpad.py
> +        if "LaunchpadPrivate" in report:
Do you want me to explicitly complain?

2024-07-17 14:38 UTC, schopin-pro commented on apport/crashdb_impl/launchpad.py
> +        if "LaunchpadPrivate" in report:
Not unless you actually *have* a problem. We don't fully understand the scope of this, what the `FIXME` was all about, etc. Let's avoid gratuitous behaviour changes, shall we?

2024-07-17 14:55 UTC, schopin-pro commented on apport/crashdb_impl/launchpad.py
> +    def _enforce_privacy_for_distro_reports(
Agreed on the misleading part, but I'd rather fix it by bringing that code back up the stack rather than splitting it further. The only reason this function exists in the first place is that I started writing the tests for it before I decided to go wider, and splitting it is just a good way to introduce unintended changes.

WDYT?

2024-07-17 15:03 UTC, bdrung commented on apport/crashdb_impl/launchpad.py
> +    def _enforce_privacy_for_distro_reports(
I am fine with moving it back to `_generate_upload_headers`

2024-07-17 15:06 UTC, bdrung commented on apport/crashdb_impl/launchpad.py
> +        if "LaunchpadPrivate" in report:
crashdb-conf.md says:
> Crash reports are always filed as private Launchpad bug. Bug reports are public by default, but a package hook can change this by adding a `LaunchpadPrivate` report field
It does not say that `LaunchpadPrivate` requires `DistroRelease` to be set in the report for it to work.

2024-07-17 15:33 UTC, schopin-pro commented on apport/crashdb_impl/launchpad.py
> +        if "LaunchpadPrivate" in report:
This could easily be shown as an example of scope creep. I'm here to fix the need-$arch-retrace thing. The fact that the doc doesn't match the current behaviour (which has been the same for a decade) is fairly unrelated, and changing it can have consequences that I for one don't fully understand.

Please put down the stick and let's bury that horse.

2024-07-19 14:15 UTC, schopin-pro commented on tests/unit/test_launchpad.py
> +    report["SignalName"] = "SIGABRT"
I won't sort this because some related fields would be far away from each other, but yeah, Signals should be next to each other.

2024-07-19 14:36 UTC, schopin-pro commented on tests/unit/test_launchpad.py
> +print(_f(5))
Fixed.

2024-07-19 16:50 UTC, bdrung commented on apport/crashdb_impl/launchpad.py
> +        if "LaunchpadPrivate" in report:
I was mislead and though it was about `LaunchpadPrivate`. So fixing that can go in a different merge request.

2024-07-19 16:50 UTC, bdrung approved these changes
Approved. Will merged once CI is green.

2024-07-26 09:13 UTC, bdrung requested changes

2024-07-26 09:13 UTC, bdrung commented on tests/unit/test_crashdb_launchpad.py
> +    assert not re.match(r"need-[a-z0-9]-retrace", headers.get("Tags", ""))
Have you tested that test to fail before the fix is applied? I tried that and found two issues here:
```suggestion
    assert not re.search(r"need-[a-z0-9]+-retrace", headers.get("Tags", ""))
```

2024-07-26 09:40 UTC, schopin-pro commented on tests/unit/test_crashdb_launchpad.py
> +    assert not re.match(r"need-[a-z0-9]-retrace", headers.get("Tags", ""))
Oh god I really hate this particular Python API. Trips me up every time.

2024-07-26 10:02 UTC, schopin-pro commented on tests/unit/test_crashdb_launchpad.py
> +    assert not re.match(r"need-[a-z0-9]-retrace", headers.get("Tags", ""))
And no, I apparently didn't run the test *before* fixing the code. Good catch!

2024-07-26 10:35 UTC, merged