Fix setuid tests due to ping dropping setcap (LP: #2089387)
canonical/apport pull request #406
Opened 2024-11-22 13:43 UTC by schopin-pro

... With a sprinkle of refactoring on top.

2024-11-22 18:00 UTC, bdrung requested changes
The ping command is not used any more in the tests. Please drop iputils-ping from the CI dependencies.

2024-11-28 13:26 UTC, schopin-pro commented on tests/integration/test_signal_crashes.py
> +            source_fd.flush()
Nice one. I'll take it and make it my own, with the following caveats:
* let's not mix both styles and use Pathlib for both paths
* `flush()` was already probably redundant in the original code as a reasonable implementation of file-like IO would flush on close, but now it's actually an error since that method doesn't exist on Path (which makes a *lot* of sense).

2024-11-28 17:02 UTC, schopin-pro commented on tests/integration/test_signal_crashes.py
> +        subprocess.run(cmd, check=True)
Done (kinda)

2024-11-28 17:03 UTC, schopin-pro commented on tests/integration/test_signal_crashes.py
> +    @unittest.skipUnless(os.path.exists("/bin/gcc"), "this test needs gcc")
I believe you're right. Fixed.

2024-11-28 17:03 UTC, schopin-pro commented
> The ping command is not used any more in the tests. Please drop iputils-ping from the CI dependencies.

Done.

2024-11-28 17:20 UTC, bdrung approved these changes

2024-11-28 17:23 UTC, merged