Disable debuginfod when collecting a report
canonical/apport pull request #6
Opened 2022-09-15 21:04 UTC by sergiodj

With the new Ubuntu debuginfod
service (https://debuginfod.ubuntu.com), and with the prospect of
having the system automatically fetch debuginfo from the internet
without user intervention, it is necessary to adjust apport to cope
with this scenario.

I had a conversation with bdmurray and he was concerned that having a
debuginfod-enabled GDB generate the corefiles that are eventually
submitted to Ubuntu can be a problem.

This commit disables GDB's debuginfod support when collecting a
report.  I chose not to touch GDB's settings on apport-retrace because
I think we should honour the user choice there.

Bug: https://launchpad.net/bugs/1989803

2022-09-16 08:36 UTC, bdrung requested changes
The change looks good. Please also update the gdb calls in the integration tests:
* tests/integration/test_report.py
* tests/integration/test_signal_crashes.py
* tests/integration/test_ui.py

The integration tests must not talk to the Internet.

2022-09-16 15:56 UTC, sergiodj commented
> The change looks good. Please also update the gdb calls in the integration tests:
> 
>     * tests/integration/test_report.py
> 
>     * tests/integration/test_signal_crashes.py
> 
>     * tests/integration/test_ui.py
> 
> 
> The integration tests must not talk to the Internet.

Thanks for the review.  I did the changes above, and also expanded the commit a little bit.  valgrind also supports debuginfod, so I went ahead and disabled the feature on it as well.  Unfortunately, valgrind doesn't provide an easy flag to disable debuginfod usage, so I had to resort to unsetting the `DEBUGINFOD_URLS` environment variable.

2022-09-20 20:04 UTC, sergiodj commented
@bdrung This is ready to be reviewed again.  Please let me know what you think.  Thanks!

2022-09-27 08:18 UTC, bdrung requested changes
You had to touch the gdb call in multiple places. I am not sure if we should refactor apport to only need to touch the gdb arguments in one place.

2022-09-27 08:18 UTC, bdrung commented on bin/apport-valgrind
> +newenviron = os.environ.copy() | {"DEBUGINFOD_URLS": ""}
This only sets the environment variable to `""` instead of unsetting it. This would be:
```
{k, v: for k, v in os.environ.items() if k != "DEBUGINFOD_URLS"}
```

2022-09-27 08:18 UTC, bdrung commented on bin/apport-valgrind
> +newenviron = os.environ.copy() | {"DEBUGINFOD_URLS": ""}
`newenviron` is not very expressive. The `new` is confusing there. How about `valgrind_env` instead (or just `env`)?

2022-09-27 08:18 UTC, bdrung commented on tests/integration/test_apport_valgrind.py
> +        newenv = self.env | {"DEBUGINFOD_URLS": ""}
Same remarks as above.

2022-09-27 08:18 UTC, bdrung commented on apport/report.py
> +        gdb_cmd += ["-iex", "set debuginfod enable off"]
How about combining those two commands into one:
```suggestion
        gdb_cmd += [
            "--batch",
            # limit maximum backtrace depth (to avoid looped stacks)
            "--ex",
            "set backtrace limit 2000",
            "-iex",
            "set debuginfod enable off",
        ]
```

2022-09-27 08:18 UTC, bdrung commented on apport/report.py
> +        # disable debuginfod
The comment "disable debuginfod" does not provide any additional information. This comment can be dropped unless it explains the "why?".

2022-09-27 18:14 UTC, sergiodj commented
Thanks for the review.  I've addressed all the points, hopefully this is good now.

2022-09-27 18:32 UTC, bdrung requested changes
Found two more points.

2022-09-27 18:32 UTC, bdrung commented on tests/integration/test_apport_valgrind.py
> +            env=valgrind_env,
You can modify `self.env` in `setUpClass` where we already modify the environment variable.

2022-09-27 18:32 UTC, bdrung commented on bin/apport-valgrind
> +)
You can use a dictionary comprehension instead of a list comprehension:
```suggestion
valgrind_env = {k: v for k, v in os.environ.items() if k != "DEBUGINFOD_URLS"}
```

2022-09-27 19:09 UTC, sergiodj commented
After a long battle with black and pylint, this is ready for review.

2022-09-27 19:27 UTC, bdrung approved these changes

2022-09-27 19:28 UTC, merged

2023-06-08 05:12 UTC, zeehio commented
Hi,

I have not been able to find a way to make apport work with the debuginfod to get the full stacktrace.

In the past I was able to provide a patch a package by myself thanks to the apport stack trace, now the symbol table information is not available neither in the GUI nor with 

```
export DEBUGINFOD_URLS="https://debuginfod.ubuntu.com"
apport-retrace --stdout _usr_bin_marco.1000.crash 
```

How am I supposed to get something instead of "No symbol table info available."?

2023-06-08 08:39 UTC, bdrung commented
Yes, you should get a stack trace presented instead.